title: New Year!
author: Happy_Gnom
email: dopemail@happy.com
description: > # this means to ignore newlines until "baseurl:"
  Boys and girls! The Great holliday is comming and we better be prepaired for it! Let's get started!

# social links
github_username:  https://github.com/HappyGnom

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
